task: train
trainer: arlb
autoregressive: true
auto_resume: true
resume_ckpt: null
max_iters: 10000000000000
seed: 42
distribution_loss: diffusion
wandb_entity: zhenxu.zx
wandb_project: wgl
sharding_strategy: hybrid_full
fs_size: 8
sp_size: 8
generator_cpu_offload: true
mixed_precision: true
generator_fsdp_wrap_strategy: lambda
text_encoder_fsdp_wrap_strategy: size
forward_prefetch: false
gradient_checkpointing: true
load_text_encoder: true
text_encoder_cpu_offload: true
attn_block_compile: true
text_encoder_compile: false
vae_compile: false
optim_compile: false
lr: 0.0
sa_lr: 0.0
qk_lr: 0.0
ca_lr: 0.0
ca_qk_lr: 0.0
ar_lr: 1.0e-05
warmup_steps: 0
weight_decay: 0.01
beta1: 0.9
beta2: 0.999
clip_grad_norm: 10.0
warn_loss: 0.5
warn_loss_start_step: 100
num_train_timesteps: 1000
gradient_accumulation_steps: 1
save_interval: 500
max_checkpoints: 3
ema_weight: 0
ema_start_step: 500
gc_interval: 100
save_artifacts_interval: 1000
new_shape_artifact_save_interval: 0
empty_cache_warmup_steps: 1
empty_cache_interval: 0
high_low_switch_interval: 16
chunk_size: 5
context_noise: 0.2
context_noise_std: 0.1
context_scale: 1.0
history_dropout_ratio: 0.1
tf_df_mix: false
df_probability: 0.5
tf_f_ratio: 0.5
resampling_forcing: true
resampling_forcing_max_depth: 0
resampling_forcing_clean_chunks: 1
resampling_forcing_clean_chunks_mv_only: true
resampling_forcing_staircase: false
resampling_forcing_warmup_steps: 10000
resampling_forcing_global_sync: true
cond_image_dropout_ratio: 0.0
cond_text_dropout_ratio: 0.0
cfg_rescale_factor: 0.0
camera_cfg: false
cond_pose_dropout_ratio: 0.0
cond_image_max_frames: 5
cond_image_one_ratio: 0.99
max_cond_latent: 21
val_cond_image_frames: 1
val_cond_image_max_frames: 5
val_cond_image_one_ratio: 0.99
other_view_cond_ratio: 0.01
other_view_cond_per_view_ratio: 0.5
val_other_view_cond_ratio: 0.01
val_other_view_cond_per_view_ratio: 0.5
negative_prompt: 画面突变，色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，视频压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走，镜头晃动，画面闪烁，模糊，噪点，水印，签名，文字，变形，扭曲，液化，不合逻辑的结构，卡顿，PPT幻灯片感，过暗，欠曝，低对比度，霓虹灯光感，过度锐化，3D渲染感，电线，场景切换，交叉溶解，飞叶，乱飞的东西，误差，错误的结构，扭曲的结构，不干净的画面，肮脏的画面，穿模，点云，飞点，碎裂，morphing
model:
  model_root: lingbot_models
  model_name: lingbot-world-base-cam
  low_noise_subfolder: low_noise_model
  high_noise_subfolder: high_noise_model
  boundary: 0.947
  timestep_shift: 7.0
  num_train_timesteps: 1000
  vae_stride:
  - 4
  - 8
  - 8
  num_mm: 0
  fa4: true
  patch_size:
  - 1
  - 2
  - 2
  text_dim: 4096
  qk_norm: true
  cross_attn_norm: true
  ar_interval: 2
  prope_dim: 40
  mv_prope_dim: 42
  prope_mode: matrix
  mv_prope_mode: decomposed
  prope_tvo: false
  mv_prope_tvo: false
  decomposed_trans_mode: C
  decomposed_rot_mode: c2w
  concat_prope_dim: 0
  controlnet_init_std: 0.0
  mutex_prope_init_scale: 0.01
  base_model_history: true
  base_model_multiview: true
  ar_model_history: true
  ar_model_multiview: true
  view_attn_interval: 0
  bidirectional: false
  parallel_ar: true
  mutex_ar: false
  zero_gate: false
  clean_context_ar: false
  ckpt_group_size: 1
  selective_ckpt: false
  res_cond: false
  fps_cond: false
  scale_cond: true
  pose_cond: false
  prope_pure_t: true
  prope_unwrapped: true
inference_multiview_mode: synchronized
guidance_scale: 5.0
sampling_steps: 70
sampling_solver: unipc
timestep_shift: 10.0
use_kv_cache: true
kv_offload: true
kv_sink_size: 0
kv_window_size: 0
kv_sink_view0_only: false
kv_gpu_budget_gb: 20
kv_recompute_prefix_latents: 0
kv_offload_crossattn: true
use_uncond_kvcache: true
clean_adaln: true
context_image_fill: false
context_mask_fill: false
diffusion_forcing: false
clean_context_ar: false
max_context_t: 1000
inference_context_noise: 0.05
force_clean_history: false
decode_offload: true
vis_init: false
vis_list: []
vis_interval: 2000
vis_dir: null
vis_ema: false
vis_num_samples: 1
inference_num_samples: 8
vis_gt: true
vis_pose: true
vis_sampling_steps: 70
vis_use_kv_cache: true
raise_vis_error: false
vis_copy_to_hdfs: true
vis_hdfs_cli: /opt/tiger/arnold/hdfs_client/hdfs
vis_hdfs_dir: hdfs://harunasg/home/byte_data_seed_my2/hdd/user/zhenxu.zx/logs
vis_hdfs_copy_timeout: 300
vis_hdfs_copy_retries: 3
DEBUG: false
DEBUG_GRADIENT: false
LOG_GPU_MEMORY: false
MOCK_DATASET: false
dataset:
  data_path: ${oc.env:MVH3_DATA_ROOT}/mvgame/mvgame_15k_process/qwen3_capture_cached_video_meta_filtered_modern.parquet
  batch_size: 1
  gen_size: 20
  mv_size: 4
  height: 448
  width: 832
  overfit: false
  overfit_seq_sample:
  - 0
  - 1
  - 1
  overfit_vid_sample:
  - 0
  - 1
  - 1
  num_workers: 2
  prefetch_factor: 2
  per_worker_threads: 8
  boot_size: 0
  timeout: 0
  cycle_sampler: true
  pose_norm_target: 0
  pose_stable_factors:
  - 0.1
  - 1
  - 10
  - 100
  - 1000
  seq_sample:
  - 0
  - null
  - 1
  view_acc_abs_min: 0.5
  view_acc_abs_max: 1.5
  mv_chaos: 0.5
  off_perturb_std: 0.25
  disable_augmentation_ratio: 1.0
  type: concat
  model_fps: 16
  fps_targets:
  - 16
  image_aug: false
  gamma_correction: false
  parallel_view_decode: true
  exposure_clamp: true
  dynamic_mv_size: 1
  dynamic_gen_size: 75
  long_gen_size: 75
  long_gen_split: 0.25
  short_paths:
  - - 1
    - 75
  - - 2
    - 45
  - - 3
    - 35
  - - 4
    - 25
  - - 5
    - 20
  - - 8
    - 15
  - - 12
    - 10
  shape_pool:
  - - 8
    - 10
  - - 5
    - 15
  - - 4
    - 20
  - - 3
    - 25
  - - 2
    - 40
  - - 1
    - 75
  shape_pool_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  datasets:
  - type: mvgame
    data_path: ${oc.env:MVH3_DATA_ROOT}/mvgame/aug_qwen3_mvgame_6g_strictblack_nearclip_cut_fpsmin_walign4_wrefl_blobdense_v3.parquet
    dataset_fps: 25
    disable_augmentation_ratio: 0.0
    sampling_weight_power: 0.75
  - type: mvgame_raw
    data_path: ${oc.env:MVH3_DATA_ROOT}/mvgame/raw_video_qwen3_cached_schema_gamefilt_inherit_motioncut_nearclip_yellowfix_blurfov_nearclip2.parquet
    num_cameras: 25
    dataset_fps: 25
    video_reader: CFRVideoReader
    video_path_template: video/{c:06d}.mp4
    disable_augmentation_ratio: 0.0
    max_fov_h_deg: 100
    pre_resize: false
    image_aug: true
    gamma_correction: true
    sampling_weight_power: 0.725
  - type: egoexo4d
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/nymeria/nymeria_shape_posecuts_captioned_cached_synccleaned.parquet
    num_cameras: 2
    dataset_fps: 15
    sampling_weight_power: 0.75
    video_reader: CFRVideoReader
  - type: egoexo4d
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/egoexo4d/egoexo4d_captioned_shape_cached_repose_clean_loose_aria90.parquet
    num_cameras: 5
    dataset_fps: 30
    sampling_weight_power: 0.75
  - type: waymo_e2e
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/waymo_end2end_16fps_hq/waymo_end2end_16fps_hq_qwen3_cached_relative.parquet
    num_cameras: 8
    dataset_fps: 16
  - type: waymo_perception
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/waymo_perception_16fps_hq/waymo_perception_16fps_hq_qwen3_cached_relative.parquet
    num_cameras: 5
    dataset_fps: 16
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/dl3dv10k_yunzhi_filter/dl3dv10k_yunzhi_filter_cached_clean_relative_shape_vipe_rerun_posefiltered_shape.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_walking_hq/sekai_real_walking_hq_static_cached_relative_shape_posecuts_telecut.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid_hq_yunzhi_filtered/spatialvid_hq_yunzhi_filtered_static_cached_relative_shape_posefiltered.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/realestate10k/realestate10k_qwen3_cached_relative_shape_metric_posefiltered.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_drone/sekai_real_drone_cached_static_shape_relative_posefiltered_vlm_rescaled_slerp_drotfiltered_hoverfiltered_reposevggt.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid/spatialvid_nohq_filtered_static_posefiltered_dav3rescale_reposevggt.parquet
    sampling_weight_power: 0.675
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT}/svreal/aria/epic_fields_undist/epic_fields_undist_cut_scaled_captioned_cached.parquet
    video_reader: CFRVideoReader
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_walking_hq/sekai_real_walking_hq_dynamic_cached_relative_shape_posecuts_telecut.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid_hq_yunzhi_filtered/spatialvid_hq_yunzhi_filtered_dynamic_cached_relative_shape_f81_t3.375_posefiltered.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_drone/sekai_real_drone_cached_dynamic_shape_relative_posefiltered_vlm_rescaled_slerp_drotfiltered_hoverfiltered_reposevggt.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/dynpose100k++/dynpose100k++_cached_relative_shape_posefiltered_ratiofilt_slerp_reposevggt.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/general_ht/general_ht_480_apsect12or21_length81f_fov40or120_noposejump_shape_qwen3_cached_relative_posefiltered_dav3rescale_reposevggt.parquet
    sampling_weight_power: 0.75
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid/spatialvid_nohq_filtered_dynamic_posefiltered_dav3rescale_reposevggt.parquet
    sampling_weight_power: 0.65
val_dataset:
  data_path: ${oc.env:MVH3_DATA_ROOT}/mvgame/mvgame_15k_process/qwen3_capture_cached_video_meta_filtered_modern.parquet
  batch_size: 1
  gen_size: 20
  mv_size: 4
  height: 448
  width: 832
  overfit: false
  overfit_seq_sample:
  - 0
  - 1
  - 1
  overfit_vid_sample:
  - 0
  - 1
  - 1
  num_workers: 0
  prefetch_factor: 2
  per_worker_threads: 8
  boot_size: 0
  timeout: 0
  cycle_sampler: true
  pose_norm_target: 0
  pose_stable_factors:
  - 0.1
  - 1
  - 10
  - 100
  - 1000
  seq_sample:
  - 0
  - null
  - 1
  view_acc_abs_min: 0.5
  view_acc_abs_max: 1.5
  mv_chaos: 0.5
  off_perturb_std: 0.25
  disable_augmentation_ratio: 1.0
  sp_sharding: true
  type: concat
  model_fps: 16
  fps_targets:
  - 16
  image_aug: false
  gamma_correction: false
  parallel_view_decode: true
  exposure_clamp: true
  dynamic_mv_size: 1
  dynamic_gen_size: 75
  long_gen_size: 75
  long_gen_split: 0.25
  short_paths:
  - - 1
    - 75
  - - 2
    - 45
  - - 3
    - 35
  - - 4
    - 25
  - - 5
    - 20
  - - 8
    - 15
  - - 12
    - 10
  shape_pool:
  - - 8
    - 10
  - - 5
    - 15
  - - 4
    - 20
  - - 3
    - 25
  - - 2
    - 40
  - - 1
    - 75
  shape_pool_weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  datasets:
  - type: mvgame
    data_path: ${oc.env:MVH3_DATA_ROOT}/mvgame/aug_qwen3_mvgame_6g_strictblack_nearclip_cut_fpsmin_walign4_wrefl_blobdense_v3.parquet
    dataset_fps: 25
    disable_augmentation_ratio: 0.0
    sampling_weight_power: 0.75
  - type: mvgame_raw
    data_path: ${oc.env:MVH3_DATA_ROOT}/mvgame/raw_video_qwen3_cached_schema_gamefilt_inherit_motioncut_nearclip_yellowfix_blurfov_nearclip2.parquet
    num_cameras: 25
    dataset_fps: 25
    video_reader: CFRVideoReader
    video_path_template: video/{c:06d}.mp4
    disable_augmentation_ratio: 0.0
    max_fov_h_deg: 100
    pre_resize: false
    image_aug: true
    gamma_correction: true
    sampling_weight_power: 0.725
  - type: egoexo4d
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/nymeria/nymeria_shape_posecuts_captioned_cached_synccleaned.parquet
    num_cameras: 2
    dataset_fps: 15
    sampling_weight_power: 0.75
    video_reader: CFRVideoReader
  - type: egoexo4d
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/egoexo4d/egoexo4d_captioned_shape_cached_repose_clean_loose_aria90.parquet
    num_cameras: 5
    dataset_fps: 30
    sampling_weight_power: 0.75
  - type: waymo_e2e
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/waymo_end2end_16fps_hq/waymo_end2end_16fps_hq_qwen3_cached_relative.parquet
    num_cameras: 8
    dataset_fps: 16
  - type: waymo_perception
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/waymo_perception_16fps_hq/waymo_perception_16fps_hq_qwen3_cached_relative.parquet
    num_cameras: 5
    dataset_fps: 16
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/dl3dv10k_yunzhi_filter/dl3dv10k_yunzhi_filter_cached_clean_relative_shape_vipe_rerun_posefiltered_shape.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_walking_hq/sekai_real_walking_hq_static_cached_relative_shape_posecuts_telecut.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid_hq_yunzhi_filtered/spatialvid_hq_yunzhi_filtered_static_cached_relative_shape_posefiltered.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/realestate10k/realestate10k_qwen3_cached_relative_shape_metric_posefiltered.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_drone/sekai_real_drone_cached_static_shape_relative_posefiltered_vlm_rescaled_slerp_drotfiltered_hoverfiltered_reposevggt.parquet
  - type: static_dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid/spatialvid_nohq_filtered_static_posefiltered_dav3rescale_reposevggt.parquet
    sampling_weight_power: 0.675
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT}/svreal/aria/epic_fields_undist/epic_fields_undist_cut_scaled_captioned_cached.parquet
    video_reader: CFRVideoReader
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_walking_hq/sekai_real_walking_hq_dynamic_cached_relative_shape_posecuts_telecut.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid_hq_yunzhi_filtered/spatialvid_hq_yunzhi_filtered_dynamic_cached_relative_shape_f81_t3.375_posefiltered.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/sekai_real_drone/sekai_real_drone_cached_dynamic_shape_relative_posefiltered_vlm_rescaled_slerp_drotfiltered_hoverfiltered_reposevggt.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/dynpose100k++/dynpose100k++_cached_relative_shape_posefiltered_ratiofilt_slerp_reposevggt.parquet
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/general_ht/general_ht_480_apsect12or21_length81f_fov40or120_noposejump_shape_qwen3_cached_relative_posefiltered_dav3rescale_reposevggt.parquet
    sampling_weight_power: 0.75
  - type: dynamic
    data_path: ${oc.env:MVH3_DATA_ROOT3}/svreal/spatialvid/spatialvid_nohq_filtered_dynamic_posefiltered_dav3rescale_reposevggt.parquet
    sampling_weight_power: 0.65
profiler:
  enable: false
  skip_first: 1
  wait: 1
  warmup: 1
  active: 1
  repeat: 1
  record_shapes: true
  profile_memory: true
  with_stack: true
  with_flops: true
  with_modules: true
  record_memory_history: true
visualizer:
  layout: vertical
  font_path: assets/fonts/maple/maplecn-SemiBold.woff2
